export const MAX_WORD_LENGTH = 5
export const MAX_CHALLENGES = 6
export const ALERT_TIME_MS = 2000
export const REVEAL_TIME_MS = 350
export const GAME_LOST_INFO_DELAY = (MAX_WORD_LENGTH + 1) * REVEAL_TIME_MS
export const START_DATE = 'January 1, 2022 00:00:00' // date and time to generate the "first" word
export const NORMALIZATION = 'NFKD' // Unicode normalization for words and orthography - options: 'NFC', 'NFD', 'NKFC', 'NKFD', false
export const LANGUAGE = 'Wôpanâôt8âôk' // The display name for your language in the info modal
export const AUTHOR = 'The Wôpanâak Language Reclamation Project' // Author name in the info modal
export const AUTHOR_WEBSITE = 'https://www.wlrp.org/' // Link to author website in the info modal
